## The functions below provide the inverse of a matrix you give.
## The 2nd function will retrieve the cached value generated by the 1st
## one, if the initial matrix is identical; otherwise, it computes the 
## inverse of the matrix you name.


## makeCacheMatrix: computes and caches the inverse of a matrix "x".

makeCacheMatrix <- function(x = matrix()) {
    y<<-x               ##caches the value of the matrix you use in this function
    inverse<<-solve(x)  ##caches the inverse of the matrix used here
}


## cacheSolve: retrieves the inverse cached in makeCacheMatrix,
## if matrix "x" is identical to the one used in makeCacheMatrix.

cacheSolve <- function(x, ...) {
    if (identical(x, y)){   ##checks if matrix x here is the same used in makeCacheMatrix
        message("getting cached data")  ##message returned if using the cached inverse
        return(inverse)                 ##returns the inverse computed and cached before
    }
    else{                   ##if x is different from the x used in previous function,
        inverse2<-solve(x)  ##the inverse matrix of x will be computed and returned.
        return (inverse2)
    }
}
